### ISSUE TITLE
StromPi3_Status: not able to read device _or_ could not convert string to float

### ISSUE THREAD

**Issue by tobiasnix** [joy-it/strompi3#1]
Hello,

i am using the last firmware version (1.4) but i am not able to get the above script running.

There is a "not able to read device..." or "could not convert string to float".

```
pi@phoniebox:~ $ python StromPi3_Status.py 
Traceback (most recent call last):
  File "StromPi3_Status.py", line 90, in <module>
    sp3_date = serial_port.readline(9999);
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@phoniebox:~ $ python StromPi3_Status.py 
Traceback (most recent call last):
  File "StromPi3_Status.py", line 90, in <module>
    sp3_date = serial_port.readline(9999);
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@phoniebox:~ $ python StromPi3_Status.py 
Traceback (most recent call last):
  File "StromPi3_Status.py", line 110, in <module>
    sp3_ADC_Wide = float(serial_port.readline(9999))/1000;
ValueError: could not convert string to float: 
pi@phoniebox:~ $ python StromPi3_Status.py 
Traceback (most recent call last):
  File "StromPi3_Status.py", line 110, in <module>
    sp3_ADC_Wide = float(serial_port.readline(9999))/1000;
ValueError: could not convert string to float: 
pi@phoniebox:~ $ sudo python StromPi3_Status.py 
Traceback (most recent call last):
  File "StromPi3_Status.py", line 110, in <module>
    sp3_ADC_Wide = float(serial_port.readline(9999))/1000;
ValueError: could not convert string to float: 
```

Can somebody help?

**Comment by joy-it** [comment]
Hello,
Like described here https://github.com/joy-it/strompi3/issues/2#issuecomment-442452058, the problem can be linked to a still opened screen terminal. Also please make sure that the strompiconsole is put into its "sleepmode" with the quit-command.

Best Regards,
Jarek
