### ISSUE TITLE
serialShutdown: wrong string / shutdown does not work

### ISSUE THREAD

**Issue by tobiasnix** [joy-it/strompi3#2]
I am unable to get that script working:

Seems like the serial console sends the wrong string "xxxShtdownRaspberryPixxx" (without the "u"). But even if i change that in my serialShutdown script nothing happens.

from startstrompiconsole:
```
 FirmwareVersion: v1.4
>poweroff
xxxShtdownRaspberryPixxx
```

```
pi@phoniebox:~ $ sudo python serialShutdown.py 
^CTraceback (most recent call last):
  File "serialShutdown.py", line 18, in <module>
    x=ser.readline()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 472, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
pi@phoniebox:~ $ sudo python serialShutdown.py 
^CTraceback (most recent call last):
  File "serialShutdown.py", line 18, in <module>
    x=ser.readline()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 472, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt

```
(waiting for 20 sec before STRG + C)
In both cases the raspberry does not shutdown (from strompiconsole or from running the script manually.

**Comment by joy-it** [comment]
Hello,
it seems, that in the background you've still an opened screen (terminal) session, which is blocking the serial interface. That's why the python Script doesn't want to take over probably the shutdown command from the StromPi3.
When you are in the Screen Terminal you can close the connection with the following Keystroke-Combination: [Strg+A] -> [K] -> [Y]
To make this more clear, we'll update our manuals to make this more clearer.

Best Regards,
Jarek

**Comment by tobiasnix** [comment]
Just did an upgrade to Firmware 1.41 but its still not working.

Tried again in the console:
```
------------------------------
Welcome to the StromPi 3 Console
------------------------------
Type help to view a list of available commands.

[When you press ENTER the previous command would be executed again]

>show-status

 Time: 00:00:46
 Date: Tuesday 01.05.2018

 StromPi-Mode: mUSB -> Wide 

 WakeUp-Alarm: Disabled 
  Alarm-Mode: Time-Alarm 
  Alarm-Time: 00:00
  Alarm-Date: 01.01
  Alarm-Weekday: Monday 

 PowerOff-Alarm: Disabled 
  PowerOff-Alarm-Time: 00:00

 Raspberry Pi Shutdown: Disabled 
  Shutdown-Timer: 10 seconds

 Powerfail Warning: Enabled 

 Serial-Less Mode: Disabled 

 Battery-Level Shutdown: Disabled

 FirmwareVersion: v1.41
>poweroff
xxxShutdownRaspberryPixxx

 Raspberry Pi Shutdown

>


```
nothing happens

Through the script again:
```
pi@phoniebox:~ $ sudo python strompi3/Python-Scripts/serialShutdown.py 
^CTraceback (most recent call last):
  File "strompi3/Python-Scripts/serialShutdown.py", line 30, in <module>
    x=ser.readline()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 472, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
```
I just did a STRG+C after waiting for 60 seconds.

There is also no screen session in background:
```
pi@phoniebox:~ $ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  2.7  0.6   9520  5944 ?        Ss   10:02   0:03 /sbin/init
root         2  0.0  0.0      0     0 ?        S    10:02   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/0:0]
root         4  0.0  0.0      0     0 ?        I<   10:02   0:00 [kworker/0:0H]
root         5  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/u8:0]
root         6  0.0  0.0      0     0 ?        I<   10:02   0:00 [mm_percpu_wq]
root         7  0.0  0.0      0     0 ?        S    10:02   0:00 [ksoftirqd/0]
root         8  0.0  0.0      0     0 ?        I    10:02   0:00 [rcu_sched]
root         9  0.0  0.0      0     0 ?        I    10:02   0:00 [rcu_bh]
root        10  0.0  0.0      0     0 ?        S    10:02   0:00 [migration/0]
root        11  0.0  0.0      0     0 ?        S    10:02   0:00 [cpuhp/0]
root        12  0.0  0.0      0     0 ?        S    10:02   0:00 [cpuhp/1]
root        13  0.0  0.0      0     0 ?        S    10:02   0:00 [migration/1]
root        14  0.0  0.0      0     0 ?        S    10:02   0:00 [ksoftirqd/1]
root        15  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/1:0]
root        16  0.0  0.0      0     0 ?        I<   10:02   0:00 [kworker/1:0H]
root        17  0.0  0.0      0     0 ?        S    10:02   0:00 [cpuhp/2]
root        18  0.0  0.0      0     0 ?        S    10:02   0:00 [migration/2]
root        19  0.0  0.0      0     0 ?        S    10:02   0:00 [ksoftirqd/2]
root        20  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/2:0]
root        21  0.0  0.0      0     0 ?        I<   10:02   0:00 [kworker/2:0H]
root        22  0.0  0.0      0     0 ?        S    10:02   0:00 [cpuhp/3]
root        23  0.0  0.0      0     0 ?        S    10:02   0:00 [migration/3]
root        24  0.0  0.0      0     0 ?        S    10:02   0:00 [ksoftirqd/3]
root        25  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/3:0]
root        26  0.0  0.0      0     0 ?        I<   10:02   0:00 [kworker/3:0H]
root        27  0.0  0.0      0     0 ?        S    10:02   0:00 [kdevtmpfs]
root        28  0.0  0.0      0     0 ?        I<   10:02   0:00 [netns]
root        29  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/0:1]
root        30  0.3  0.0      0     0 ?        I    10:02   0:00 [kworker/1:1]
root        31  0.1  0.0      0     0 ?        I    10:02   0:00 [kworker/2:1]
root        32  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/3:1]
root        33  0.0  0.0      0     0 ?        S    10:02   0:00 [khungtaskd]
root        34  0.0  0.0      0     0 ?        S    10:02   0:00 [oom_reaper]
root        35  0.0  0.0      0     0 ?        I<   10:02   0:00 [writeback]
root        36  0.0  0.0      0     0 ?        S    10:02   0:00 [kcompactd0]
root        37  0.0  0.0      0     0 ?        I<   10:02   0:00 [crypto]
root        38  0.0  0.0      0     0 ?        I<   10:02   0:00 [kblockd]
root        39  0.0  0.0      0     0 ?        I<   10:02   0:00 [watchdogd]
root        40  0.0  0.0      0     0 ?        I<   10:02   0:00 [rpciod]
root        41  0.0  0.0      0     0 ?        I<   10:02   0:00 [xprtiod]
root        42  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/u8:1]
root        44  0.0  0.0      0     0 ?        S    10:02   0:00 [kswapd0]
root        45  0.0  0.0      0     0 ?        I<   10:02   0:00 [nfsiod]
root        55  0.0  0.0      0     0 ?        I<   10:02   0:00 [kthrotld]
root        56  0.0  0.0      0     0 ?        I<   10:02   0:00 [iscsi_eh]
root        57  0.0  0.0      0     0 ?        I<   10:02   0:00 [dwc_otg]
root        58  0.0  0.0      0     0 ?        I<   10:02   0:00 [DWC Notificatio]
root        59  0.0  0.0      0     0 ?        S<   10:02   0:00 [vchiq-slot/0]
root        60  0.0  0.0      0     0 ?        S<   10:02   0:00 [vchiq-recy/0]
root        61  0.0  0.0      0     0 ?        S<   10:02   0:00 [vchiq-sync/0]
root        62  0.0  0.0      0     0 ?        S    10:02   0:00 [vchiq-keep/0]
root        63  0.0  0.0      0     0 ?        S<   10:02   0:00 [SMIO]
root        64  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/2:2]
root        65  0.0  0.0      0     0 ?        S    10:02   0:00 [irq/92-mmc1]
root        66  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/1:2]
root        67  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/2:3]
root        68  0.2  0.0      0     0 ?        S    10:02   0:00 [mmcqd/0]
root        69  0.0  0.0      0     0 ?        S    10:02   0:00 [jbd2/mmcblk0p2-]
root        70  0.0  0.0      0     0 ?        I<   10:02   0:00 [ext4-rsv-conver]
root        71  0.0  0.0      0     0 ?        I<   10:02   0:00 [ipv6_addrconf]
root       100  0.5  0.4  12792  4364 ?        Ss   10:02   0:00 /lib/systemd/systemd-journald
root       121  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/0:2]
root       123  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/3:2]
root       124  0.4  0.3  14340  3268 ?        Ss   10:02   0:00 /lib/systemd/systemd-udevd
root       147  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/u8:2]
root       223  0.0  0.0      0     0 ?        I<   10:02   0:00 [cfg80211]
root       225  0.0  0.0      0     0 ?        I<   10:02   0:00 [brcmf_wq/mmc1:0]
root       226  0.0  0.0      0     0 ?        S    10:02   0:00 [brcmf_wdog/mmc1]
systemd+   269  0.1  0.3  17280  3492 ?        Ssl  10:02   0:00 /lib/systemd/systemd-timesyncd
root       312  0.0  0.4   7380  4212 ?        Ss   10:02   0:00 /lib/systemd/systemd-logind
avahi      319  0.1  0.2   6404  2824 ?        Ss   10:02   0:00 avahi-daemon: running [phoniebox.l
root       323  0.0  0.2  23748  2468 ?        Ssl  10:02   0:00 /usr/sbin/rsyslogd -n
nobody     324  0.0  0.2   5296  2444 ?        Ss   10:02   0:00 /usr/sbin/thd --triggers /etc/trig
message+   338  0.1  0.3   6492  3464 ?        Ss   10:02   0:00 /usr/bin/dbus-daemon --system --ad
avahi      352  0.0  0.1   6404  1600 ?        S    10:02   0:00 avahi-daemon: chroot helper
root       367  0.0  0.2   5296  2436 ?        Ss   10:02   0:00 /usr/sbin/cron -f
root       396  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/1:3]
root       401  0.0  0.4  10144  3900 ?        Ss   10:02   0:00 wpa_supplicant -B -c/etc/wpa_suppl
root       419  0.0  0.0      0     0 ?        I    10:02   0:00 [kworker/3:3]
root       459  0.0  0.0      0     0 ?        I<   10:02   0:00 [kworker/2:1H]
root       470  0.0  0.1   2948  1724 ?        Ss   10:02   0:00 /sbin/dhcpcd -q -w
root       482  0.0  0.1   4196  1384 tty1     Ss+  10:02   0:00 /sbin/agetty --noclear tty1 linux
root       484  0.0  0.4  10208  4656 ?        Ss   10:02   0:00 /usr/sbin/sshd -D
root       586  0.4  0.6  11528  5728 ?        Ss   10:03   0:00 sshd: pi [priv]
pi         593  0.0  0.5   9656  5060 ?        Ss   10:03   0:00 /lib/systemd/systemd --user
pi         596  0.0  0.1  11184  1252 ?        S    10:03   0:00 (sd-pam)
pi         603  0.0  0.3  11528  3420 ?        S    10:03   0:00 sshd: pi@pts/0
pi         606  0.8  0.4   6204  4356 pts/0    Ss   10:03   0:00 -bash
pi         652  0.0  0.3   7740  2872 pts/0    R+   10:04   0:00 ps aux
```

My /boot/config.txt:

```
pi@phoniebox:~ $ cat /boot/config.txt 
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi
dtoverlay=pi3-miniuart-bt
# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
enable_uart=1
```

Any idea whats wrong with my setup?
